### ISSUE TITLE
[BUG] overlapping

### ISSUE THREAD

**Issue by schmelto** [nhcarrigan/nhcarrigan.github.io#329]
# Bug Report

## Describe the bug

![image](https://user-images.githubusercontent.com/30869493/117703532-0b897500-b1ca-11eb-9b93-857f771253b7.png)

the project images overlapping with the 
![image](https://user-images.githubusercontent.com/30869493/117703576-180dcd80-b1ca-11eb-9e52-1ea7e398aa6c.png)
maybe set the z-index of this little bit higher

**Comment by nhcarrigan** [comment]
The border is actually a background image and is intentionally behind everything to avoid accidentally obscuring content.

**Comment by schmelto** [comment]
OK yeah due it looks little bit like a picture frame I thought it would be in the  front 🙈 but yeah accidentally obscuring content will be a big issue if you bring this on top :D

**Comment by nhcarrigan** [comment]
Going to close this for now as a `wontfix`. We can certainly re-evaluate the border background, though.
