### ISSUE TITLE
[OTHER]- Padding between Images

### ISSUE THREAD

**Issue by Prathamesh-Shanbhag** [nhcarrigan/nhcarrigan.github.io#330]
# Other Issues
Works Page Images
## Describe the issue
- Padding between Images on My works page

- Add padding between images for clear margins

## Additional information
![image](https://user-images.githubusercontent.com/70568620/117703827-c2e0b480-b1e7-11eb-992f-a73887054a7a.png)

**Comment by nhcarrigan** [comment]
Yes, this should be resolved. Maybe I'll divide them with `<hr>` elements. 🤔
