### ISSUE TITLE
Remove the horizontal scrollbar

### ISSUE THREAD

**Issue by Skyhero-admin** [nhcarrigan/nhcarrigan.github.io#337]
The site looks really cool now,
I don't know if it's a problem but I have a suggestion to remove the bottom horizontal scrollbar 
I know that in CSS we can remove it with overflow-x:hidden;
But since I don't know how to make changes here I thought I should let you know

**Comment by nhcarrigan** [comment]
Could you share a screenshot where you've got the horizontal scrollbar? I can't reproduce it on my end.

**Comment by Skyhero-admin** [comment]
ohk
I think others can't see it , maybe it's just my screen 
![scrollbar](https://user-images.githubusercontent.com/74371107/117760867-02d58500-b244-11eb-936d-3fd1ff78709e.png)
It's right below the running link, it's not an issue but I thought that you might not know about it so I raised an issue

**Comment by nhcarrigan** [comment]
It's because you have a vertical scrollbar - which... I'm not sure why.

**Comment by Skyhero-admin** [comment]
Can I try fixing it ?

**Comment by Skyhero-admin** [comment]
I'll try to see why this might be happening

**Comment by nhcarrigan** [comment]
I don't think so. The `nav` already has a `100vw` width.

**Comment by Skyhero-admin** [comment]
I tried changing the nav and particles width to 100% and the horizontal scrollbar disappeared

**Comment by nhcarrigan** [comment]
Do the particles still cover the entire viewport though?

**Comment by Skyhero-admin** [comment]
yes

**Comment by Skyhero-admin** [comment]
I changed the width using developer tools so I dont know how it will be in the PR but I will send one
