### ISSUE TITLE
[BUG] -  cursor should be Highlights once application run and also some guidelines.

### ISSUE THREAD

**Issue by mindexpert7546** [nhcarrigan/nhcarrigan.github.io#350]
### What bug did you encounter?

Once I opened the application I got confused, what to do next where do I need to type and what? After 2-5 minutes only get the idea. 

### What did you expect to happen?

Required : 
1. Once the application is run then cursor should be highlighted on the terminal.
2. Once the application runs the first time the guidelines should appear.
3. Add Placeholder value also for the command input

**Comment by naomi-lgbt** [comment]
The boot screen specifically mentions "Please enter commands below:". Additional instruction is not needed, and forcing focus onto the input would be an accessibility antipattern.

A placeholder would also diminish the aesthetic of the site.

**Comment by naomi-lgbt** [comment]
Closing as decayed
