### ISSUE TITLE
Temporary certificate error

### ISSUE THREAD

**Issue by mattszymanko** [nhcarrigan/nhcarrigan.github.io#370]
Looks like it's okay now, but perhaps you should know about it. There was just a temporary error with your certificate, which caused Google Chrome to mark your website as unsafe. I don't think it was anything on my side, but it still happened only for a moment.

**Comment by nhcarrigan** [comment]
The certificate is provisioned through GitHub Pages, which every so often seems to have a hiccup. 🙁

**Comment by mattszymanko** [comment]
Okay, sure, I even expected that. As I said, it's probably not that bad, though I just thought you may wanna know about this little incident. Either way, good luck. I'm closing the issue now.
