### ISSUE TITLE
[BUG] Mesage label Alignment in Contact Form

### ISSUE THREAD

**Issue by Prathamesh-Shanbhag** [nhcarrigan/nhcarrigan.github.io#405]
# Bug Report
Mesage label Alignment is incorrect

## Screenshots
![nhcarrigan](https://user-images.githubusercontent.com/70568620/120098825-aa641a00-c155-11eb-8706-994e4041d44e.png)

## Additional information
I will try and solve this issue too.

**Comment by nhcarrigan** [comment]
Closed as outdated after latest redesign.
