### ISSUE TITLE
Can't see some text on your website!!!

### ISSUE THREAD

**Issue by Srijandev** [nhcarrigan/nhcarrigan.github.io#462]
The first few passage of your [website](https://www.nhcarrigan.com/) like `Welcome` message and `About Me` are so much white that I can't see the written text, you should use the same text theme in that passages like you have done in `Projects`(Purple theme looks cool and readable) 

- This passage is quite unreadable
![image](https://user-images.githubusercontent.com/67185450/128038295-7ede94ca-ed17-44db-921b-4e08f92298e4.png)

- This passage is readable and looks good
![image](https://user-images.githubusercontent.com/67185450/128039038-4ebfcaf7-e43d-49c0-a294-b3f9812cbffc.png)

Thanks for reading till here, I hope everything makes sense to you! ❤️

**Comment by nhcarrigan** [comment]
![image](https://user-images.githubusercontent.com/63889819/128039355-9973f7c6-9d40-42d4-907f-75ca83efa337.png)

Do you have a browser extension that might be modifying the page?

**Comment by Srijandev** [comment]
Yeah I have forced dark mode in my browser, so it was my fault lol 

Thanks 👍🏽
