### ISSUE TITLE
[FEAT] - UI redesign 

### ISSUE THREAD

**Issue by Onyelaudochukwuka** [nhcarrigan/nhcarrigan.github.io#61]
### What feature would you like to see?

I would love a design with more of a modern UI as the current UI is a bit outdated.

### Additional information

I'll love to take this on if assigned to me.
Questions:
- Can I have a theme color change of necessary?
- Can I have a layout change?
- Can I add asthetic features like watermarks, animations, ... To the design?

**Comment by naomi-lgbt** [comment]
We want to keep the colour theme - purple is our aesthetic.

Do you have some mocks you'd like to share?

**Comment by naomi-lgbt** [comment]
Closing as stale.
